export const INDEX_WEIGHTS_FALLBACK_META = {
  NVDA: {
    tickerId: 1150,
    nameEn: "NVIDIA Corporation",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/NVDA.svg",
    slug: "nvda",
  },
  AAPL: {
    tickerId: 146,
    nameEn: "Apple Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/AAPL.svg",
    slug: "aapl",
  },
  MSFT: {
    tickerId: 575,
    nameEn: "Microsoft Corporation",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/MSFT.svg",
    slug: "msft",
  },
  AMZN: {
    tickerId: 562,
    nameEn: "Amazon.com, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/AMZN.svg",
    slug: "amzn",
  },
  AVGO: {
    tickerId: 14539,
    nameEn: "Broadcom Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/AVGO.svg",
    slug: "avgo",
  },
  META: {
    tickerId: 36222,
    nameEn: "Meta Platforms, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/META.svg",
    slug: "meta",
  },
  GOOGL: {
    tickerId: 148893,
    nameEn: "Alphabet Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/GOOGL.svg",
    slug: "googl",
  },
  TSLA: {
    tickerId: 16123,
    nameEn: "Tesla, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/TSLA.svg",
    slug: "tsla",
  },
  ORCL: {
    tickerId: 663,
    nameEn: "Oracle Corporation",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/ORCL.svg",
    slug: "orcl",
  },
  GOOG: {
    nameEn: "Alphabet Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/GOOG.svg",
    slug: "goog",
  },
  MU: {
    tickerId: 1309,
    nameEn: "Micron Technology, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/MU.svg",
    slug: "mu",
  },
  AMD: {
    tickerId: 1016,
    nameEn: "Advanced Micro Devices, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/AMD.svg",
    slug: "amd",
  },
  TSM: {
    tickerId: 1534,
    nameEn: "Taiwan Semiconductor Manufacturing Company Limited",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/TSM.svg",
    slug: "tsm",
  },
  PLTR: {
    tickerId: 554416,
    nameEn: "Palantir Technologies Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/PLTR.svg",
    slug: "pltr",
  },
  LRCX: {
    tickerId: 1181,
    nameEn: "Lam Research Corporation",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/LRCX.svg",
    slug: "lrcx",
  },
  AMAT: {
    tickerId: 1132,
    nameEn: "Applied Materials, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/AMAT.svg",
    slug: "amat",
  },
  INTC: {
    tickerId: 1017,
    nameEn: "Intel Corporation",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/INTC.svg",
    slug: "intc",
  },
  TXN: {
    nameEn: "Texas Instruments Incorporated",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/TXN.svg",
    slug: "txn",
  },
  KLAC: {
    tickerId: 1793,
    nameEn: "KLA Corporation",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/KLAC.svg",
    slug: "klac",
  },
  ADI: {
    nameEn: "Analog Devices, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/ADI.svg",
    slug: "adi",
  },
  SHOP: {
    nameEn: "Shopify Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/SHOP.svg",
    slug: "shop",
  },
  ASML: {
    tickerId: 1715,
    nameEn: "ASML Holding N.V.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/ASML.svg",
    slug: "asml",
  },
  QCOM: {
    nameEn: "QUALCOMM Incorporated",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/QCOM.svg",
    slug: "qcom",
  },
  PANW: {
    nameEn: "Palo Alto Networks, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/PANW.svg",
    slug: "panw",
  },
  APP: {
    nameEn: "AppLovin Corporation",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/APP.svg",
    slug: "app",
  },
  INTU: {
    nameEn: "Intuit Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/INTU.svg",
    slug: "intu",
  },
  WDC: {
    nameEn: "Western Digital Corporation",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/WDC.svg",
    slug: "wdc",
  },
  CRWD: {
    nameEn: "CrowdStrike Holdings, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/CRWD.svg",
    slug: "crwd",
  },
  ADBE: {
    nameEn: "Adobe Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/ADBE.svg",
    slug: "adbe",
  },
  MRVL: {
    nameEn: "Marvell Technology, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/MRVL.svg",
    slug: "mrvl",
  },
  STX: {
    nameEn: "Seagate Technology Holdings plc",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/STX.svg",
    slug: "stx",
  },
  SNPS: {
    nameEn: "Synopsys, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/SNPS.svg",
    slug: "snps",
  },
  CDNS: {
    nameEn: "Cadence Design Systems, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/CDNS.svg",
    slug: "cdns",
  },
  PDD: {
    nameEn: "PDD Holdings Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/PDD.svg",
    slug: "pdd",
  },
  DASH: {
    nameEn: "DoorDash, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/DASH.svg",
    slug: "dash",
  },
  FTNT: {
    nameEn: "Fortinet, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/FTNT.svg",
    slug: "ftnt",
  },
  MPWR: {
    nameEn: "Monolithic Power Systems, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/MPWR.svg",
    slug: "mpwr",
  },
  NXPI: {
    nameEn: "NXP Semiconductors N.V.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/NXPI.svg",
    slug: "nxpi",
  },
  ADSK: {
    nameEn: "Autodesk, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/ADSK.svg",
    slug: "adsk",
  },
  TRI: {
    nameEn: "Thomson Reuters Corporation",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/TRI.svg",
    slug: "tri",
  },
  MSTR: {
    nameEn: "Strategy Inc",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/MSTR.svg",
    slug: "mstr",
  },
  MCHP: {
    nameEn: "Microchip Technology Incorporated",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/MCHP.svg",
    slug: "mchp",
  },
  DDOG: {
    nameEn: "Datadog, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/DDOG.svg",
    slug: "ddog",
  },
  ROP: {
    nameEn: "Roper Technologies, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/ROP.svg",
    slug: "rop",
  },
  CTSH: {
    nameEn: "Cognizant Technology Solutions Corporation",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/CTSH.svg",
    slug: "ctsh",
  },
  WDAY: {
    nameEn: "Workday, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/WDAY.svg",
    slug: "wday",
  },
  ARM: {
    nameEn: "Arm Holdings plc",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/ARM.svg",
    slug: "arm",
  },
  ZS: {
    nameEn: "Zscaler, Inc.",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/ZS.svg",
    slug: "zs",
  },
  TEAM: {
    nameEn: "Atlassian Corporation",
    iconLight: "https://static.seekingalpha.com/cdn/s3/company_logos/mark_vector_light/TEAM.svg",
    slug: "team",
  },
};
